nervosnetwork/docs.nervos.org

- website/core/Footer.js
- website/siteConfig.js
- website/static/css/custom.css
- website/static/js/extra.js
Note: the legacy site url is configured as `https://docs-old.nervos.org` which is **NOT** accessible ATM. Should it require update/change we can simple change `oldDocSiteUrl` from `siteConfig.js`.
The banner HTML is put inside `Footer.js`, which is the only point we can customize (docusaurus v1.x). HTML element placed there is difficult to position at our need, so I added an `extra.js` which moves the banner to top on page load.
> Banner link to old docs

- website/static/css/custom.css
The anchor positioning is 40px(from old site announcement bar) more than it actually is, resulting in the header not being visible when the link is clicked.
This issue is particularly prominent in long articles like: 
https://docs.nervos.org/docs/basics/glossary#block-time
> fix: anchor positioning

- website/docs/basics/concepts/ckb-vm.md
- website/docs/essays/rfcs.md
1. Javascript -> JavaScript
2. comma after space
> docs: fix typos

- website/docs/basics/guides/ckb-on-windows.md
[Fix a missing link.](https://docs.nervos.org/docs/basics/guides/ckb-on-windows#install-tools-with-scoop) which was deleted since #58.
> fix: a missing link

- website/docs/basics/guides/devchain.md
- website/docs/basics/guides/mainnet.md
- website/docs/basics/guides/neuron.md
- website/docs/basics/guides/testnet.md
- website/docs/labs/capsule-dynamic-loading.md
Between a Html tag and a Markdown code block tag, there should be a blank line.
Check [original page of "Run a CKB Dev Blockchain"](https://github.com/nervosnetwork/docs-new/blob/c644e98d71fd0d908dc81412e051b34794c7ca0c/website/docs/basics/guides/devchain.md#6-start-the-ckb-miner) and [fixed page of it](https://github.com/nervosnetwork/docs-new/blob/f15af6c240f3818137dadd52b3ed0637bb8a6ef1/website/docs/basics/guides/devchain.md#6-start-the-ckb-miner) to see the differences.
Run the follow code to fix the preview pages which rendered by GitHub flavored Markdown.
```bash
find . -name "*.md" | while read f; do
sed -i ':a;N;N;$!ba;s@\(</summary>\)\n\(```\)@\1\n\n\2@g' "${f}"
sed -i ':a;N;N;$!ba;s@\(```\)\n\(</details>\)@\1\n\n\2@g' "${f}"
done
```
> fix: the preview pages which rendered by GitHub flavored Markdown

- website/docs/basics/guides/devchain.md
Also add code block around `ckb` because otherwise ckb and CKB in one sentence occur with different case.
> Fix grammar issue in devchain docs

- website/docs/labs/sudtbycapsule.md
The use of inputs capacity is misleading, it  should be input tokens
> Fix(docs): Use the right term, "tokens" instead of "capacity"

- website/docs/integrate/qa.md
Update answers for:
- Why is it that the minimum transfer amount cannot be less than 61 CKB?
- If I have 100 CKB in my address and transfer 61 CKB, the balance remaining (39 CKB) isn’t enough to create a change cell. How should I handle this?
> Update answers on transfer minimums.

- website/docs/basics/guides/mainnet.md
- website/docs/basics/guides/monitor-nodes.md
- website/sidebars.json
Updated previous essay on running a CKB mainnet node, included another approach of running a public PRC node. Also added instructions on node monitoring using CkbGuardian.
> docs: add content on running public RPC node and node monitoring

- website/docs/labs/capsule-exec.md
- website/docusaurus.config.js
I have updated the capsule exec doc for ckb-std >= 0.11.
Ckb-std now passes exec args via `ckb_std::env::argv`, and uses `core::ffi::CStr`.
Full code of the test is included.
Also added syntax highlighting for rust code.
> Update capsule exec doc

- website/docs/basics/guides/devchain.md
```console
error: Found argument '--tx-fee' which wasn't expected, or isn't valid in this context
Did you mean '--max-tx-fee'?
If you tried to supply `--tx-fee` as a PATTERN use `-- --tx-fee`
USAGE:
wallet transfer --to-address <to-address> --capacity <capacity> --from-account <from-account> --max-tx-fee <capacity>
```
> Fix parameter error in guide

- website/docs/reference/rpc.md
Add a note to send_transaction explaining that returning the transaction hash does not guarantee the status of the transaction, and that it is recommended to track the status of the transaction via get_transaction
> Add description of send_transaction

- website/docs/integrate/sdk.md
Testnet Faucet is built on ckb-sdk-ruby
Ref: https://github.com/Magickbase/ckb-testnet-faucet/
> docs: update SDK description

- website/docs/labs/capsule-dynamic-loading.md
- website/docs/labs/sudtbycapsule.md
https://discord.gg/n6tx7uC is expired.
> Fix the expired Discord invite link

- website/static/js/extra.js
the old-doc site will be redirected to the Vercel branch. 
the source code of the old-doc site is located in branch `v1`
- https://github.com/nervosnetwork/docs.nervos.org/tree/v1
> chore: redirect old-doc to v1 vercel

- .github/workflows/deploy.yaml
**Issue**
Github pages deployments failing because GITHUB_TOKEN does not have adequate permissions.
**Fix:**
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defining-access-for-the-github_token-scopes
> fix: Github token permission for GH deployment

- website/static/js/extra.js
Description:
- I'm leveraging the aa-Input class to identify search input fields and trigger a GA event ('search') when users press the ENTER key, ensuring search terms are captured and sent as "event_label"
To test:
- Go to "Realtime" and look for "search" under the Event widget
> Send search terms to GA

- website/docs/getting-started/create-dob.mdx
- website/docs/getting-started/create-token.mdx
- website/docs/getting-started/dev-environment.mdx
- website/docs/getting-started/devtool.md
- website/docs/getting-started/getting-started.mdx
- website/docs/getting-started/how-ckb-works.mdx
- website/docs/getting-started/transfer-ckb.mdx
- website/docs/getting-started/write-message.mdx
https://nervos-ckb-docs-git-fork-retricsu-add-how-ckb-works-cryptape.vercel.app/docs/getting-started/how-ckb-works
> Add how ckb works

- website/docs/getting-started/how-ckb-works.mdx
Description:
- fix several broken links & a typo on how ckb works
> fix broken link & typo on how-ckb-works

- website/docs/getting-started/quick-start.mdx
- website/docs/script/ScriptHeaders.tsx
- website/docs/script/_ScriptTools.mdx
- website/docs/script/a-minimal-script.mdx
- website/docs/script/js-script.mdx
Description:
- Fix the broken link around ckb-script-templates
- Make the tools you need for script development consistent across different pages
- Use "info" instead of "note" when describing tools or versions
> fix: broken link & tools for scripts

- website/docs/dapp/write-message.mdx
- website/docs/getting-started/how-ckb-works.mdx
- website/docs/getting-started/quick-start.mdx
- website/docs/script/ScriptHeaders.tsx
- website/docs/script/intro-to-script.mdx
- website/docs/tech-explanation/args.md
- website/docs/tech-explanation/capacity.md
- website/docs/tech-explanation/cell-model.md
- website/docs/tech-explanation/cell.md
- website/docs/tech-explanation/code-hash.md
- website/docs/tech-explanation/hash-type.md
- website/docs/tech-explanation/script.md
- website/sidebars.js
- website/src/css/customTheme.css
Description:
- Add Cell, Script, capacity, code_hash, hash_type, args files under tech-explanation
- Remove the previous Cell section from cell-model
- Update internal links accordingly
> add files to tech explanation

- website/.husky/pre-commit
- website/.prettierignore
- website/package.json
- website/yarn.lock
Description
- automatically run yarn fmt && git add . when committing using husky
> Add pre-commit

- website/package.json
- website/yarn.lock
**Reason for downgrade**
Due to an incompatibility between Docusaurus v3.4 and the cmfcmf local search plugin, we are experiencing issues with incorrect search URLs. This downgrade is necessary to restore correct search functionality and ensure a smooth user experience.
> core: Downgrade docusaurus

- website/docs/script/spawn_direct_cross-script_calling.mdx
- website/sidebars.js
> docs: Spawn direct cross-script calling

- website/docs/getting-started/installation.mdx
- website/src/components/TutorialHeader/index.tsx
change the ccc mini version to `v0.0.14-alpha.0` since our `examples` use ccc `v0.0.14-alpha.0`. Later, we should upgrade the version in examples and then bump the required minimal version in docs.
> chore: ccc mini version

- examples/simple-lock/README.md
- website/docs/dapp/simple-lock.mdx
* deploy script with type-id.
* Change the CKB of deposit in the document to a smaller value, otherwise new users cannot minting so much ckb in a short time under the default configuration (the unit of offckb deposit is ckb).
> fix simple-lock: deploy script with type-id

- README.md
Update the production branch as `master`, so now we can develop on the default branch `develop` and it is less confusing.
> update readme production branch

- website/src/components/Tooltip/index.tsx
- website/src/components/Tooltip/styles.module.css
Fix: https://github.com/nervosnetwork/docs.nervos.org/issues/638
Description: 
1. Render tooltip with createPortal so it’s no longer clipped by parent containers.
2. Assign a unique id to each tooltip and reference it via aria-describedby for screen reader support.
> fix: tooltip clipping issue
