nervosnetwork/docs.nervos.org

website/docs/essays/developer-materials-guide.md, website/sidebars.json
This pull request adds the "Developer Materials Guide" page to the Essays section.
=> Add "Developer Materials Guide" page.

website/docs/basics/guides/run-ckb-with-docker.md
> devchain.md#3-configure-the-block-assembler
=> fix(docs): update the link to [Configure the Block Assembler]

website/docs/basics/guides/get-ckb.md
- CKB for Windows is no longer experimental
- update ckb build requirements
=> update ckb build requirements

website/yarn.lock
=> upgrade yarn.lock 

.github/workflows/test-deploy.yml
=> add test-deploy.yaml

website/docs/basics/guides/neuron.mdx, website/docs/essays/introduction-to-ckb-studio.mdx, website/docs/essays/lifecycle.mdx, website/docs/essays/polyjuice.mdx
migrate `md` to `mdx`, and use the JSX syntax to tell Docusaurus@2 how to find a media resource
https://docusaurus.io/docs/static-assets
=> fix: cannot find images

website/docs/essays/developer-materials-guide.md
When the references page was published, only part one of the 3-part series was linked.
=> Include links to part 2 and 3 of Programming CKB series

website/docs/basics/concepts/nervos-blockchain.md
Just some misspellings I've found while reading the documentation.
=> Update nervos-blockchain.md misspellings

website/docs/basics/guides/mining-ckb.md, website/sidebars.json
This commit adds a guide for users that are new to mining on how to get started on Nervos.
=> Add mining page.

website/docusaurus.config.js, website/package.json, website/yarn.lock
this PR supported rendering math equation via KaTeX or MathJax
preview: https://nervos-ckb-docs-git-math-equation-cryptape.vercel.app/docs/essays/tx-confirmation
=> feat: rendering math equation

website/docs/essays/mint-sudt-via-contract.md
=> fix sudt transaction typo

website/docs/reference/halving.md
fixed the halving.md Block/Daily rewards value
=> fixed the halving.md Block/Daily rewards value

website/docs/basics/glossary.md
updated the definition of light node, full node, and mining node. delated pruned node.
=> docs: update node types.md

website/docs/basics/glossary.md
1. Add an explanation of cycle concept.
2. Add an concept of feerate, it is a bitcoin concept, but it is used in many places and there's no explanation of it, so I think we should give a little explanation about that.
=> doc: revising concept of cycles and feerate

website/docs/basics/guides/mainnet.md
- fixed typo, clarified language
- removed the concept of GitBash
- added command for using git in cmd on windows
=> Update "How to run a main node"

website/docs/integrate/sdk.md
- Add `ckb-sdk-rust`
- Update `ckb-sdk-go`'s link to `nervosnetwork/ckb-sdk-go`
=> Update ckb sdk infos

website/docs/basics/concepts/cell-model.md, website/docs/basics/glossary.md, website/docs/basics/guides/devchain.md, website/docs/essays/ckb-core-dev.md, website/docs/essays/polyjuice.mdx, website/docs/integrate/qa.md, website/docs/labs/lumos-nervosdao.md, website/docs/labs/sudtbycapsule.md, website/docs/reference/cell.md, website/src/pages/index.js
Fixed many typos by [typos-cli](https://github.com/crate-ci/typos)
=> Fix many typos

website/docs/essays/lifecycle.mdx
Request for review @zhangsoledad @doitian
=> Fix Transaction Validation Lifecycle

website/docs/reference/intro.md
=> fix: halving reference

website/docs/dev-environment.mdx, website/docusaurus.config.js, website/package.json, website/src/css/customTheme.css, website/src/css/customVariables.css, website/src/prism/dark.js, website/src/prism/light.js, website/yarn.lock
Description:
1. Installed prism-react-renderer and customized theme based on vsLight and vsDark (prism's default themes) for our light and dark mode
2. Applied new code block styling to both light and dark mode (Following screenshots are how it will look like)
=> Update styling of codeblock

examples/simple-transfer/index.tsx, examples/simple-transfer/lib.ts, examples/simple-transfer/package.json, examples/simple-transfer/tsconfig.json, examples/xudt/lib.ts, website/docs/dapp/DApp.mdx, website/docs/dapp/create-custom-token.md, website/docs/dapp/view-and-transfer-balance.md
This is pretty rough but you get the idea. some preview link: 
- https://github.com/RetricSu/docs.nervos.org/blob/xudt-create/website/docs/dapp/create-custom-token.md
- https://github.com/RetricSu/docs.nervos.org/blob/xudt-create/website/docs/dapp/view-and-transfer-balance.md
- https://nervos-ckb-docs-git-fork-retricsu-xudt-create-cryptape.vercel.app/docs/
=> feat: create-custom-token & transfer docs and testnet sandbox

website/docs/dapp/create-nft.md, website/docs/dapp/write-and-read-on-chain-message.md
=> Edit Tutorial Content

website/docs/rpcs.mdx, website/src/css/customTheme.css
Description
- Added Public JSON RPC Nodes & Basic Usage sections to the RPCs page
- Updated minor styling around table of contents & code
=> Update the RPCs page

website/docs/dapp/CardsContents.tsx, website/docs/dapp/DApp.mdx, website/src/components/TutorialFrame/index.jsx
=> update: text updates and styling

website/docs/dapps/CardsContents.tsx, website/docs/dapps/DApps.mdx
=> fix: dapp links

website/docs/dapps/create-dob.mdx, website/docs/dapps/issue-token.mdx, website/docs/dapps/transfer-balance.mdx, website/docs/dapps/write-message.mdx, website/docs/dev-environment.mdx, website/docusaurus.config.js
Description:
1. Simplify all the subtitles in all tutorials & dev environment
2. Fix grammar & Update some contents (e.g. ckb binary version) & styling in dev environment
3. Update the discord link
=> Simplify wording in tutorials & dev environment

website/docs/concepts/glossary.md
=> Glossary v2: script xudt added

website/docusaurus.config.js
=> docs: update twitter/x label

website/package.json, website/src/components/CookieConsent/index.tsx, website/src/components/CookieConsent/styles.module.css, website/src/pages/index.tsx, website/yarn.lock
1. Integrate logrocket into the website
2. Added a Cookie consent banner to the home page (status is stored in localStorage)
=> Add logrocket & cookie consent

website/docs/getting-started/quick-start.mdx, website/src/css/customTheme.css, website/src/css/customVariables.css, website/src/prism/dark.js, website/src/prism/light.js, website/src/theme/CodeBlock/Container/styles.module.css
**Description**
- Refined grammar, corrected typos, and restructured the quick-start.mdx file for improved flow
- Updated some color variables for enhanced visual appeal.
=> update quickstart and some colors

examples/simple-transfer/index.tsx, examples/simple-transfer/lib.ts, website/docs/dapp/transfer-ckb.mdx
context:
- https://github.com/nervosnetwork/DevRel/discussions/2#discussioncomment-9250008
=> refactor: simplify transfer tutorial

website/docs/dapp/TutorialOverview.tsx, website/docs/dapp/simple-lock.mdx, website/src/components/TutorialHeader/index.tsx, website/src/components/TutorialHeader/styles.module.css
Description:
- Proofread and fix typos for Build a Simple Lock tutorial
- Update the TutorialHeader component to make the "Script develop tools" collapsible
=> Update simple lock tutorial

website/docs/ecosystem/organizations.md, website/docs/getting-started/quick-start.mdx, website/docusaurus.config.js, website/sidebars.js, website/src/pages/homeContents.tsx, website/src/theme/NotFound/Content/index.js
Description
- Add "Organizations" under ecosystem
- Update the discord links to https://discord.gg/4Jcw8MwEEv
=> Add organizations & update discord links

website/docs/serialization/encoding-specs.mdx, website/docs/serialization/example-role-playing-game.mdx, website/docs/serialization/schema-language.mdx, website/docs/serialization/tools.mdx, website/docs/serialization/use-in-ckb-scripts.mdx
Description:
1. Fix the grammar link in schema-language.mdx 
2. Fix the table layout of Memory layout in encoding-specs
3. Assign specific programming language to code blocks in all serialization files
=> fix grammar link & table & assign specific language to code block

website/docusaurus.config.js, website/static/js/extra.js
Description:
Add a list of auto-redirects using plugin-client-redirects
Note:
The JS logic to auto-redirect was removed in #400
=> add more auto-redirects

website/docs/common-scripts/spore-dob-0.mdx, website/docs/common-scripts/spore-protocol.mdx, website/sidebars.js
Description
- Add spore protocol and spore dob-0 as two separated pages in the common-scripts section
=> feat(docs): add spore protocol & spore dob-0

website/docs/getting-started/blockchain-networks.mdx, website/docs/node/rpcs.mdx, website/src/components/CopyLink/index.tsx, website/src/components/CopyLink/styles.module.css
**Description**
Create a CopyLink component to address the issue where clicking on the RPC links triggers a download instead of copying the URL to the clipboard.
=> feat: Fix rpc link issue

website/docs/script/debug-script.mdx
Description:
- Fixed grammar and improved text clarity.
- Added installation instructions for macOS users
- Included a section for additional resources
=> feat (docs): update the contents of debug-script

website/docs/sdk-and-devtool/ccc.mdx, website/sidebars.js, website/src/pages/homeContents.tsx
* Introducing CCC as the primary SDK for CKB development
* Updated landing page by replacing Lumos with ccc
=> docs: add SDK-CCC

website/docs/getting-started/how-ckb-works.mdx, website/docs/script/intro-to-script.mdx, website/docs/sdk-and-devtool/cli-tool.mdx
=> rephrasing & typo fixing

website/docs/history-and-hard-forks/intro-to-hard-fork.mdx, website/sidebars.js, website/src/components/Home/index.tsx, website/src/css/customTheme.css, website/src/pages/index.tsx, website/static/svg/icon-sidebar-history.svg, website/static/svg/illus-history.svg
1. Add a "History & Hard Forks" section
2. Add intro to hardfork (https://www.notion.so/cryptape/Intro-to-Hardfork-1318f0d3781e80e2ac77e72e1e4672e9)
3. Update "Unveil Latest Updates" to "Unveil Updates & Evolution" on the landing page for people to access history & hard forks quicker (Figma link: https://www.figma.com/design/WIrbDAZH7Cm1RyfDXaBLVE/Documentation?node-id=28003-9157&t=U5kidUtYQv0oF6sF-1).
=> doc: Add intro to hard fork

website/docs/history-and-hard-forks/ckb-hard-fork-history.mdx, website/sidebars.js, website/src/components/HardForkTime/index.tsx, website/src/components/HardForkTime/styles.module.css
Add "CKB Hard Fork History" under History & Hard Fork section
Note: launch date, epoch number, and tools & updates for CKB2024 will be added in another PR
=> docs: CKB Hard Fork History

website/docs/history-and-hard-forks/history-vm-version.mdx, website/docs/tech-explanation/ckb-vm.md, website/sidebars.js
depends on https://github.com/nervosnetwork/docs.nervos.org/pull/498
=> doc: add vm-history in hardforks

website/docs/script/sudt-script.mdx
in response to this issue: https://github.com/ckb-devrel/offckb/issues/205#issuecomment-2561611204
=> docs: improve language accuracy of sudt script tutorial

website/docusaurus.config.js, website/sidebars.js, website/src/css/customTheme.css, website/src/theme/Navbar/MobileSidebar/Header/index.tsx, website/src/theme/Navbar/MobileSidebar/Layout/index.tsx, website/src/theme/Navbar/MobileSidebar/index.tsx, website/src/theme/Navbar/index.tsx
Description:
- Added 4 navbar links ( Nodes & Mining, Ecosystem, History, Resources ) to separate specific content from the original Docs section. This allows each category to have its own dedicated space.
- Updated the editURL for Blog
- Swizzled the Navbar/MobileSidebar component to adjust its responsiveness
=> feat: Restructure navbar

website/docs/history-and-hard-forks/ckb-hard-fork-history.mdx, website/src/components/HardForkTime/index.tsx
updated info: mainnet launch date, epoch number, and mainnet binary version
=> docs: update meepo hardfork info

examples/rust-script-examples/Cargo.lock, examples/rust-script-examples/Cargo.toml, examples/rust-script-examples/contracts/spawn-child/.gitignore, examples/rust-script-examples/contracts/spawn-child/Cargo.toml, examples/rust-script-examples/contracts/spawn-child/Makefile, examples/rust-script-examples/contracts/spawn-child/README.md, examples/rust-script-examples/contracts/spawn-child/src/lib.rs, examples/rust-script-examples/contracts/spawn-child/src/main.rs, examples/rust-script-examples/contracts/spawn-parent/.gitignore, examples/rust-script-examples/contracts/spawn-parent/Cargo.toml, examples/rust-script-examples/contracts/spawn-parent/Makefile, examples/rust-script-examples/contracts/spawn-parent/README.md, examples/rust-script-examples/contracts/spawn-parent/src/lib.rs, examples/rust-script-examples/contracts/spawn-parent/src/main.rs, examples/rust-script-examples/tests/src/tests.rs, website/docs/script/ckb-script-ipc.mdx, website/docs/script/rust/rust-api-spawn.mdx, website/sidebars.js
This PR depends on https://github.com/nervosnetwork/docs.nervos.org/pull/555
* [IPC in CKB On-chain Script](https://www.notion.so/cryptape/IPC-in-CKB-On-chain-Script-A-Deep-Dive-into-ckb-script-ipc-Library-1a78f0d3781e8066ac70f98dec03c199#1a78f0d3781e817ebc2af11c82b92d6a)
* Rust spawn call description
* Example about spawn
=> Docs: add Spawn

website/src/css/customTheme.css
Description:
- Remove the unexpected margin from second-level categories
=> fix: update the styling of second-level category

website/docs/getting-started/how-ckb-works.mdx, website/docs/integrate-wallets/intro-to-wallets.mdx, website/docs/sdk-and-devtool/CardsContents.tsx, website/docs/sdk-and-devtool/devtool.md, website/docs/sdk-and-devtool/lumos.mdx, website/docs/tech-explanation/capacity-mini.md, website/sidebars.js
Modifications include:
- Added a note on Lumos SDK
- Added a minimal cell capacity technical explanation
- Updated the dev tools page: removed the "Development & Deployment" category and added a Debug Script link under "CKB-Debugger"
=> Update sdk & dev tools info and add minimal capacity explanation

website/docs/node/node-configuration.mdx
Description:
- Added a new "Node Discoverability" section to the Node Configuration page.
- Includes information about the `HolePunching` protocol introduced in CKB v0.202.0.
=> feat: Update node config to include holepunching

website/docs/script/intro-to-script.mdx, website/docs/tech-explanation/data-type-diff.md, website/sidebars.js
Description:
1. Added Data Hash vs. Type Hash to tech-explanation > Scripts
2. Added related contents to Script > Intro to Scripts
=> feat: Add Data Hash vs. Type Hash

website/docs/tech-explanation/data-type-diff.md
Description:
- Update 'Why This Design Matters' section to emphasize benefits of decoupling Script logic from VM versions
=> feat: update why data and type hash matter

examples/xudt/index.tsx, examples/xudt/package-lock.json, examples/xudt/package.json
Update parcel to 2.15.4 to fix bug in linux:
```
Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-linux-x64-glibc
```
Parcel related issues: https://github.com/parcel-bundler/watcher/issues/152
=> Update example/xudt  package.json

website/docs/dapp/_SwitchToTestnet.mdx, website/docs/dapp/_SwitchToTestnet.tsx, website/docs/dapp/create-dob.mdx, website/docs/dapp/create-token.mdx, website/docs/dapp/simple-lock.mdx, website/docs/dapp/transfer-ckb.mdx, website/docs/dapp/write-message.mdx, website/docs/getting-started/quick-start.mdx, website/docs/script/rust/rust-example-minimal-script.mdx, website/docs/script/rust/rust-example-spawn-script.mdx, website/docs/script/rust/rust-example-sudt-script.mdx, website/docs/sdk-and-devtool/offckb.mdx, website/docs/serialization/ccc-molecule.mdx, website/src/css/customTheme.css, website/src/theme/CodeBlock/Container/styles.module.css, website/src/theme/CodeBlock/Content/styles.module.css
Description:
- Update the URL that points to doc/examples from develop branch to master branch
- Update the SwitchToTestnet to tsx to activate readmeLink
- Update the styling of codeBlock
=> fix: update url from develop to master

website/docs/script/script-testing-guide.md, website/sidebars.js
add script/smart contract testing guide
=> docs: add script/smart contract testing guide

website/docs/ecosystem/organizations.md
Description:
- Add APP5Labs in org & remove magickbase
=> feat: update org info

website/docs/dapp/create-dob.mdx, website/docs/dapp/create-token.mdx, website/docs/dapp/simple-lock.mdx, website/docs/dapp/transfer-ckb.mdx, website/docs/dapp/write-message.mdx
* fix(docs): make download dApp source code with correct branch
* fix build
=> fix(docs): make download dApp source code with correct branch (#680)
